name: weather_forcast
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  provider: ^6.1.2
  gif: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/day-clear.png
    - assets/images/day-cloudy.png
    - assets/images/day-rain.png
    - assets/images/day-snow.png
    - assets/images/day-wind.png
    - assets/images/night-clear.png
    - assets/images/night-cloudy.png
    - assets/images/night-rain.png
    - assets/images/night-snow.png
    - assets/images/night-wind.png

    - assets/icons/clear-day.png
    - assets/icons/clear-night-dark.png
    - assets/icons/clear-night-light.png
    - assets/icons/day-cloudy.png
    - assets/icons/night-cloudy-dark.png
    - assets/icons/night-cloudy-light.png
    - assets/icons/fog-dark.png
    - assets/icons/fog-light.png
    - assets/icons/rain.png
    - assets/icons/snow.png
    - assets/icons/windy.png
